services:
  postgres:
    image: postgres:16
    container_name: grpc_demo
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: grpc_demo
    ports:
      - "5432:5432"
